### ISSUE TITLE
Not working on Nexus 7 4.4 

### ISSUE THREAD

**Issue by johnnycannuk** [iSECPartners/Android-SSL-TrustKiller#1]
When I try to install, I get the following:

XXXXX:platform-tools xxxxx$ ./adb install /Users/xxxxx/Downloads/Android-SSL-TrustKiller.apk 
5262 KB/s (258231 bytes in 0.047s)
java.lang.NoSuchMethodException: getSystemSharedLibraryNames [int]
    at java.lang.Class.getConstructorOrMethod(Class.java:472)
    at java.lang.Class.getMethod(Class.java:857)
    at com.devadvance.rootcloakplus.Main.initForPackageManager(Main.java:45)
    at com.devadvance.rootcloakplus.Main.initialize(Main.java:31)
    at dalvik.system.NativeStart.main(Native Method)
    pkg: /data/local/tmp/Android-SSL-TrustKiller.apk

Cydia is installed and the device was rebooted.

**Comment by mblanchou** [comment]
You probably need to disable SElinux for Cydia Substrate to work on 4.4 (you can use https://play.google.com/store/apps/details?id=com.mrbimc.selinux&hl=en to do so).

**Comment by johnnycannuk** [comment]
That seems to have it installed (same error though). It is not showing up in the app list.

**Comment by johnnycannuk** [comment]
Just read your blog post...seems to be working. I'll test it out later.

Thanks
